# Generated by Django 5.2.1 on 2025-05-30 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_carrier_shipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('symbol', models.CharField(max_length=5)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, help_text='Exchange rate relative to a base currency (e.g., USD).', max_digits=10)),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default currency for the system?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id_external', models.CharField(help_text='ID from the payment gateway, e.g., Stripe charge ID.', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('authorization', 'Authorization'), ('capture', 'Capture'), ('void', 'Void')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('requires_action', 'Requires Action')], default='pending', max_length=20)),
                ('payment_method_details', models.CharField(blank=True, help_text="e.g., 'Visa ending in 1234'", max_length=255, null=True)),
                ('gateway_response_raw', models.TextField(blank=True, help_text='Raw response from the payment gateway for debugging.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the transaction.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.currency')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='shop.order')),
                ('parent_transaction', models.ForeignKey(blank=True, help_text='For linking refunds/captures to original payments/authorizations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_transactions', to='finance.transaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
