# Generated by Django 5.2.1 on 2025-05-30 04:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_url', models.CharField(help_text='Absolute URL of the page. E.g., /products/my-product-slug or https://example.com/about', max_length=2000, unique=True)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Last modification date of the content at this URL.')),
                ('priority', models.DecimalField(choices=[(Decimal('0.1'), '0.1'), (Decimal('0.2'), '0.2'), (Decimal('0.3'), '0.3'), (Decimal('0.4'), '0.4'), (Decimal('0.5'), '0.5 (Default)'), (Decimal('0.6'), '0.6'), (Decimal('0.7'), '0.7'), (Decimal('0.8'), '0.8'), (Decimal('0.9'), '0.9'), (Decimal('1.0'), '1.0 (Highest)')], decimal_places=1, default=Decimal('0.5'), max_digits=2)),
                ('change_frequency', models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='weekly', max_length=10)),
            ],
            options={
                'verbose_name': 'Sitemap Entry',
                'verbose_name_plural': 'Sitemap Entries',
                'ordering': ['-priority', '-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'description', 'keywords', 'og:title'", max_length=255)),
                ('content', models.TextField(help_text='The value of the meta tag.')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='cms_metatag_content_3ba025_idx')],
                'unique_together': {('name', 'content_type', 'object_id')},
            },
        ),
    ]
