# Generated by Django 5.2.1 on 2025-05-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique key for the setting, e.g., 'SITE_TITLE', 'SIDEBAR_LAYOUT'.", max_length=100, unique=True)),
                ('value', models.TextField(help_text="Value of the setting. Store as string, parse based on 'value_type'. For JSON, store valid JSON.")),
                ('value_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('json', 'JSON'), ('text', 'Text Area')], default='string', help_text="The data type of the setting's value.", max_length=10)),
                ('group', models.CharField(blank=True, default='general', help_text="Group for organizing settings, e.g., 'general', 'seo', 'theme'.", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of what this setting is for.')),
                ('is_public', models.BooleanField(default=False, help_text='If true, this setting can be exposed via a public API endpoint.')),
                ('is_editable', models.BooleanField(default=True, help_text='If false, this setting can only be changed via code/migrations, not via API/admin.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group', 'key'],
            },
        ),
    ]
